name: Scrape kokumin BBS

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium chromedriver-binary beautifulsoup4

      - name: Prepare Chrome for Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Run scraper with headless Chrome
        run: python scrape_kokumin.py

      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "kokumin bbs"
          git commit -m "Update kokumin bbs captures" || echo "No changes to commit"
          git push
